apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ template "backendhelm.fullname" . }}-kubernetestest
  labels:
    kg-app-deployment: app-claim0
  name: app-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
