apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ template "backendhelm.fullname" . }}-kubernetestest
  creationTimestamp: null
  labels:
    kg-app-deployment: redis
  name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
